image: golang:latest

services:
    - docker:dind

variables:
  REPO_NAME: gitlab.com/paranoidsecurity/cachedns
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - go get

stages:
    - test
    - build
    - release

format:
    stage: test
    script:
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet $(go list ./... | grep -v /vendor/)
      - go test -race $(go list ./... | grep -v /vendor/)

compile:
    stage: build
    script:
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o $CI_PROJECT_DIR/cachedns .
    artifacts:
      paths:
        - cachedns

build:
    image: docker:stable
    stage: build
    script:
        - docker pull $CONTAINER_IMAGE:latest || true
        - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_BUILD_REF .
        - docker push $CONTAINER_IMAGE:$CI_BUILD_REF

release:
    image: docker:stable
    stage: release
    script:
        - docker pull $CONTAINER_IMAGE:$CI_BUILD_REF
        - docker tag $CONTAINER_IMAGE:$CI_BUILD_REF $CONTAINER_IMAGE:latest
        - docker push $CONTAINER_IMAGE:latest
    only:
        - master
